# Generated by Django 3.0.4 on 2020-03-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_lat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_lng', models.DecimalField(decimal_places=2, max_digits=20)),
                ('end_lat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('end_lng', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelWayPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=20)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Travel')),
            ],
        ),
        migrations.CreateModel(
            name='TravelTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=20)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Travel')),
            ],
        ),
    ]
