# Generated by Django 3.0.4 on 2020-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200309_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travel_type_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='travel_type_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
